services:
  db:
    image: postgres:16
    container_name: palaj-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: palaj_db
    ports:
      - "5432:5432"
    volumes:
      - palaj_pg_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: palaj-api
    depends_on:
      - db
    env_file:
      - backend/.env.docker
    ports:
      - "8000:8000"

volumes:
  palaj_pg_data:
